//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.02 at 12:06:16 AM IST 
//


package com.schema.pkg;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ipnb_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ipnb_t"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="NBAPIPAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SCTPPortNumber" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="WBTSid" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ipnb_t", propOrder = {
    "nbapipAddress",
    "sctpPortNumber",
    "wbtSid"
})
public class IpnbT {

    @XmlElement(name = "NBAPIPAddress", required = true)
    protected String nbapipAddress;
    @XmlElement(name = "SCTPPortNumber", required = true)
    protected BigInteger sctpPortNumber;
    @XmlElement(name = "WBTSid", required = true, defaultValue = "65535")
    protected BigInteger wbtSid;

    /**
     * Gets the value of the nbapipAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNBAPIPAddress() {
        return nbapipAddress;
    }

    /**
     * Sets the value of the nbapipAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNBAPIPAddress(String value) {
        this.nbapipAddress = value;
    }

    /**
     * Gets the value of the sctpPortNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSCTPPortNumber() {
        return sctpPortNumber;
    }

    /**
     * Sets the value of the sctpPortNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSCTPPortNumber(BigInteger value) {
        this.sctpPortNumber = value;
    }

    /**
     * Gets the value of the wbtSid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWBTSid() {
        return wbtSid;
    }

    /**
     * Sets the value of the wbtSid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWBTSid(BigInteger value) {
        this.wbtSid = value;
    }

}
