//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.02 at 12:06:16 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.com/schema/pkg.1#raml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.schema.pkg;
