//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.02 at 12:06:16 AM IST 
//


package com.schema.pkg;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RNCName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="RNCIPAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="WBTS" type="{http://www.com/schema/pkg.1#raml}wbts_t" maxOccurs="unbounded"/&gt;
 *         &lt;element name="IPNB" type="{http://www.com/schema/pkg.1#raml}ipnb_t" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rncName",
    "rncipAddress",
    "wbts",
    "ipnb"
})
@XmlRootElement(name = "RNC")
public class RNC {

    @XmlElement(name = "RNCName", required = true)
    protected String rncName;
    @XmlElement(name = "RNCIPAddress", required = true)
    protected String rncipAddress;
    @XmlElement(name = "WBTS", required = true)
    protected List<WbtsT> wbts;
    @XmlElement(name = "IPNB", required = true)
    protected List<IpnbT> ipnb;

    /**
     * Gets the value of the rncName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRNCName() {
        return rncName;
    }

    /**
     * Sets the value of the rncName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRNCName(String value) {
        this.rncName = value;
    }

    /**
     * Gets the value of the rncipAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRNCIPAddress() {
        return rncipAddress;
    }

    /**
     * Sets the value of the rncipAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRNCIPAddress(String value) {
        this.rncipAddress = value;
    }

    /**
     * Gets the value of the wbts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wbts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWBTS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WbtsT }
     * 
     * 
     */
    public List<WbtsT> getWBTS() {
        if (wbts == null) {
            wbts = new ArrayList<WbtsT>();
        }
        return this.wbts;
    }

    /**
     * Gets the value of the ipnb property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ipnb property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIPNB().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IpnbT }
     * 
     * 
     */
    public List<IpnbT> getIPNB() {
        if (ipnb == null) {
            ipnb = new ArrayList<IpnbT>();
        }
        return this.ipnb;
    }

}
