//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.02 at 12:06:16 AM IST 
//


package com.schema.pkg;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for wbts_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wbts_t"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="WBTSName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BTSIPAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="WCEL" type="{http://www.com/schema/pkg.1#raml}wcel_t" maxOccurs="24"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wbts_t", propOrder = {
    "wbtsName",
    "btsipAddress",
    "wcel"
})
public class WbtsT {

    @XmlElement(name = "WBTSName", required = true)
    protected String wbtsName;
    @XmlElement(name = "BTSIPAddress", required = true)
    protected String btsipAddress;
    @XmlElement(name = "WCEL", required = true)
    protected List<WcelT> wcel;

    /**
     * Gets the value of the wbtsName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWBTSName() {
        return wbtsName;
    }

    /**
     * Sets the value of the wbtsName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWBTSName(String value) {
        this.wbtsName = value;
    }

    /**
     * Gets the value of the btsipAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBTSIPAddress() {
        return btsipAddress;
    }

    /**
     * Sets the value of the btsipAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBTSIPAddress(String value) {
        this.btsipAddress = value;
    }

    /**
     * Gets the value of the wcel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wcel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWCEL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WcelT }
     * 
     * 
     */
    public List<WcelT> getWCEL() {
        if (wcel == null) {
            wcel = new ArrayList<WcelT>();
        }
        return this.wcel;
    }

}
