//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.02 at 12:06:16 AM IST 
//


package com.schema.pkg;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for wcel_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wcel_t"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CellIdentity" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="CellName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ADJx" type="{http://www.com/schema/pkg.1#raml}adjx_t"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wcel_t", propOrder = {
    "cellIdentity",
    "cellName",
    "adJx"
})
public class WcelT {

    @XmlElement(name = "CellIdentity", required = true)
    protected BigInteger cellIdentity;
    @XmlElement(name = "CellName", required = true)
    protected String cellName;
    @XmlElement(name = "ADJx", required = true)
    protected AdjxT adJx;

    /**
     * Gets the value of the cellIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCellIdentity() {
        return cellIdentity;
    }

    /**
     * Sets the value of the cellIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCellIdentity(BigInteger value) {
        this.cellIdentity = value;
    }

    /**
     * Gets the value of the cellName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCellName() {
        return cellName;
    }

    /**
     * Sets the value of the cellName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCellName(String value) {
        this.cellName = value;
    }

    /**
     * Gets the value of the adJx property.
     * 
     * @return
     *     possible object is
     *     {@link AdjxT }
     *     
     */
    public AdjxT getADJx() {
        return adJx;
    }

    /**
     * Sets the value of the adJx property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdjxT }
     *     
     */
    public void setADJx(AdjxT value) {
        this.adJx = value;
    }

}
